version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: userservice_db
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
  app:
    build: ..
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: userservice_db
      DB_SSLMODE: disable
      DB_TIMEZONE: UTC
      PORT: 8080
      JWT_SECRET: your_jwt_secret_key
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db-data: