version: 'v3'

networks:
  app:
    driver: bridge

volumes:
  postgres-data:
  pgadmin-data:

services:
  auth-service:
    build: ../backend/auth-service
    container_name: auth-service
    environment:
      DEFAULT_ADMIN_LOGIN: ${DEFAULT_ADMIN_LOGIN}
      DEFAULT_ADMIN_EMAIL: ${DEFAULT_ADMIN_EMAIL}
      DEFAULT_ADMIN_PASSWORD: ${DEFAULT_ADMIN_PASSWORD}
      DB_HOST: db-user-service
      DB_PORT: ${DB_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - app

  game-plugins-service:
    build: ../game-plugins-service
    container_name: game-plugins-service
    networks:
      - app

  db-user-service:
    container_name: db-user-service
    image: postgres:17.2-alpine3.20
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./postgresql-config/init-scripts:/docker-entrypoint-initdb.d
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - app

  user-service:
    build: ../real-user-service
    container_name: user-service
    environment:
      DB_HOST: db-user-service
      DB_PORT: ${DB_PORT}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      DB_SSLMODE: disable
      DB_TIMEZONE: UTC
      PORT: 8080
      JWT_SECRET: your_jwt_secret_key
    ports:
      - "8080:8080"
    depends_on:
      - db-user-service
    networks:
      - app

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ../redis:/root/redis
      - ../redis/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_PASSWORD=12345
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
    networks:
      - app

  game-room-service:
    build: ../service
    container_name: game-room-service
    networks:
      - app
    depends_on:
      - redis

  nginx:
    image: nginx:1.21
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8888:8888"
    networks:
      - app
    depends_on:
      - game-plugins-service
      - auth-service
      - game-room-service
      - user-service